version: 1.0

services:
  - name: member-management-api
    source:
      type: git
      url: https://github.com/your-username/member-management.git
      branch: main
    build:
      type: nodejs
      version: 18
    deploy:
      replicas: 1
      resources:
        cpu: 0.5
        memory: 512Mi
      env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: 3000
        - name: MONGODB_URI
          value: mongodb://ppadun9_user:ppadun8267@mongodb:27017/member-management
        - name: MONGODB_USERNAME
          value: ppadun9_user
        - name: MONGODB_PASSWORD
          value: ppadun8267
        - name: MONGODB_DATABASE
          value: member-management
        - name: JWT_SECRET
          value: your-jwt-secret-key
      ports:
        - port: 3000
          protocol: http
      healthcheck:
        path: /health
        port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3

  - name: mongodb
    source:
      type: image
      image: mongo:6.0
    deploy:
      replicas: 1
      resources:
        cpu: 0.5
        memory: 512Mi
      env:
        - name: MONGO_INITDB_DATABASE
          value: member-management
        - name: MONGO_INITDB_ROOT_USERNAME
          value: ppadun9_user
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: ppadun8267
      ports:
        - port: 27017
          protocol: tcp
      volumes:
        - name: mongodb-data
          mountPath: /data/db
          size: 1Gi

volumes:
  - name: mongodb-data
    type: persistent 