services:
  - type: web
    name: member-management-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_USERNAME
        value: ppadun9_user
      - key: MONGODB_PASSWORD
        sync: false
      - key: MONGODB_DATABASE
        value: member-management
      - key: JWT_SECRET
        sync: false 