services:
  - type: web
    name: member-management-system
    env: node
    buildCommand: echo "Render 배포 환경 - 빌드 완료"
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: member-management
      - key: MONGODB_USERNAME
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: DEPLOYMENT_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    plan: free 